find . -name "*.stats" > all

cat all | perl -ne 'chomp; $f=$_; ($j,$p,$j2)=split(/\//,$f); $s=`fgrep "ntron chain level" $f | cut -d"|" -f 1`; chomp($s); print "$p\t$s\n";' > all.sensitivity
cat all | perl -ne 'chomp; $f=$_; ($j,$p,$j2)=split(/\//,$f); $s=`fgrep "ntron chain level" $f | cut -d"|" -f 3`; chomp($s); print "$p\t$s\n";' > all.fsensitivity
cat all | perl -ne 'chomp; $f=$_; ($j,$p,$j2)=split(/\//,$f); $s=`fgrep "ntron chain level" $f | cut -d"|" -f 2`; chomp($s); print "$p\t$s\n";' > all.precision
cat all | perl -ne 'chomp; $f=$_; ($j,$p,$j2)=split(/\//,$f); $s=`fgrep "ntron chain level" $f | cut -d"|" -f 4`; chomp($s); print "$p\t$s\n";' > all.fprecision

#cat all.precision | perl -ne 'chomp; $z=$_; $z=~s/ +//g; ($n,$c)=split(/\t/,$z); ($d,$t,$v,$comp)=split(/_/,$n); $d=uc($d); $t=uc($t); $comp=uc($comp); $comp=~s/RAW//; $comp="ALL_ANNOT" if($comp eq "ALL"); $k1=$t; $k2=$comp; if($d eq "SKBR3") {  $k1=$d."_".$t; if($comp ne "ALL_ANNOT" && $comp ne "G029") { $k2=$d."_".$comp; }} $h{$k1}->{$k2}=$c; $h2{$k2}=1; END { $i=0; print "Sample"; map { print "\t$_"; } sort keys %h2; print "\n"; for $k (sort keys %h) { $i++; print $k; for $k2 (sort keys %h2) { print "\t".$h{$k}->{$k2}; } print "\n"; }}' > all.precision.tsv
cat all.precision | perl -ne 'chomp; $z=$_; $z=~s/ +//g; ($n,$c,$total)=split(/\t/,$z); ($d,$t,$v,$comp)=split(/_/,$n); $d=uc($d); $t=uc($t); $comp=uc($comp); $comp=~s/RAW//; $comp="ALL_ANNOT" if($comp eq "ALL"); $k1=$t; $k2=$comp; if($d eq "SKBR3") {  $k1=$d."_".$t; if($comp ne "ALL_ANNOT" && $comp ne "G029") { $k2=$d."_".$comp; }} $h{$k1}->{$k2}=($c,$total); $h2{$k2}=1; END { $i=0; print "Sample"; map { print "\t$_"; } sort keys %h2; print "\n"; for $k (sort keys %h) { $i++; print $k; for $k2 (sort keys %h2) { print "\t".$h{$k}->{$k2}->[1]." (".$h{$k}->{$k2}->[0]."%)"; } print "\n"; }}' > all.precision.tsv

cat all.fprecision | perl -ne 'chomp; $z=$_; $z=~s/ +//g; ($n,$c)=split(/\t/,$z); ($d,$t,$v,$comp)=split(/_/,$n); $d=uc($d); $t=uc($t); $comp=uc($comp); $comp=~s/RAW//; $comp="ALL_ANNOT" if($comp eq "ALL"); $k1=$t; $k2=$comp; if($d eq "SKBR3") {  $k1=$d."_".$t; if($comp ne "ALL_ANNOT" && $comp ne "G029") { $k2=$d."_".$comp; }} $h{$k1}->{$k2}=$c; $h2{$k2}=1; END { $i=0; print "Sample"; map { print "\t$_"; } sort keys %h2; print "\n"; for $k (sort keys %h) { $i++; print $k; for $k2 (sort keys %h2) { print "\t".$h{$k}->{$k2}; } print "\n"; }}' > all.fprecision.tsv

cat all.sensitivity | perl -ne 'chomp; $z=$_; $z=~s/Intron chain level://; $z=~s/ +//g; ($n,$c)=split(/\t/,$z); ($d,$t,$v,$comp)=split(/_/,$n); $d=uc($d); $t=uc($t); $comp=uc($comp); $comp=~s/RAW//; $comp="ALL_ANNOT" if($comp eq "ALL"); $k1=$t; $k2=$comp; if($d eq "SKBR3") {  $k1=$d."_".$t; if($comp ne "ALL_ANNOT" && $comp ne "G029") { $k2=$d."_".$comp; }} $h{$k1}->{$k2}=$c; $h2{$k2}=1; END { $i=0; print "Sample"; map { print "\t$_"; } sort keys %h2; print "\n"; for $k (sort keys %h) { $i++; print $k; for $k2 (sort keys %h2) { print "\t".$h{$k}->{$k2}; } print "\n"; }}' > all.sensitivity.tsv

cat all.fsensitivity | perl -ne 'chomp; $z=$_; $z=~s/Intron chain level://; $z=~s/ +//g; ($n,$c)=split(/\t/,$z); ($d,$t,$v,$comp)=split(/_/,$n); $d=uc($d); $t=uc($t); $comp=uc($comp); $comp=~s/RAW//; $comp="ALL_ANNOT" if($comp eq "ALL"); $k1=$t; $k2=$comp; if($d eq "SKBR3") {  $k1=$d."_".$t; if($comp ne "ALL_ANNOT" && $comp ne "G029") { $k2=$d."_".$comp; }} $h{$k1}->{$k2}=$c; $h2{$k2}=1; END { $i=0; print "Sample"; map { print "\t$_"; } sort keys %h2; print "\n"; for $k (sort keys %h) { $i++; print $k; for $k2 (sort keys %h2) { print "\t".$h{$k}->{$k2}; } print "\n"; }}' > all.fsensitivity.tsv
